// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_MENU_H
#define _UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_menu_res.h"

#ifdef USE_GX4900_MODEL
// SCREEN: ui_menu

//ui_menu.c



//ui_menu_events.c
extern void ui_menu_set_type_icon(ui_menu_para_t * menu_para);
extern void ui_list_folder_create(ui_menu_para_t * menu_para, bool focused);
extern void ui_list_folder_destroy(ui_menu_para_t * menu_para);
extern void * ui_menu_create(explr_list_para_t* ui_list_para, __u32 mode);
extern void ui_menu_destroy(void * para);
extern void ui_menu_suspend(void * para);
extern void ui_menu_resume(void * para);
#else
// SCREEN: ui_menu
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_menu_top;
extern lv_obj_t * ui_menu_back;
extern lv_obj_t * ui_menu_content;
extern lv_obj_t * ui_menu_content_bg;
extern lv_obj_t * ui_settings_browse;





//ui_menu_events.c
extern void ui_menu_set_type_icon(ui_menu_para_t * menu_para);
//extern void ui_list_folder_create(ui_menu_para_t * menu_para, bool focused);
//extern void ui_list_folder_destroy(ui_menu_para_t * menu_para);
extern void ui_menu_create(explr_list_para_t* ui_list_para, __u32 mode);
extern void ui_menu_destroy(void);
extern void ui_menu_suspend(void);
extern void ui_menu_resume(void);
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
