// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui_menu.h"

#if 1//USE_LOG_PRINT
	#define __menu_msg(...)			(eLIBs_printf("Menu MSG:L%d:", __LINE__),				 \
													  eLIBs_printf(__VA_ARGS__)) 
#else
	#define __menu_msg(...)
#endif

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_menu
void ui_menu_screen_init(ui_menu_para_t * menu_para);

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif



void ui_menu_suspend(void * para)
{
	ui_menu_para_t * menu_para = (ui_menu_para_t *)para;
	
	lv_obj_add_flag(menu_para->ui_menu, LV_OBJ_FLAG_HIDDEN);      /// Flags
}

void ui_menu_resume(void * para)
{
	ui_menu_para_t * menu_para = (ui_menu_para_t *)para;
	
	lv_obj_clear_flag(menu_para->ui_menu, LV_OBJ_FLAG_HIDDEN);      /// Flags
}


static void * ui_list_del_all_item(ui_menu_para_t * menu_para)
{
	__u32 child_cnt, i;

	//__menu_msg("menu_para->ui_list_para->media_type=%d\n", menu_para->ui_list_para->media_type);
	if(menu_para->ui_list_para->media_type == RAT_MEDIA_TYPE_PIC)
	{
		if(menu_para->ui_list_para->lbar_del)
		{
			child_cnt = lv_obj_get_child_cnt(menu_para->ui_menu_list);
			//__menu_msg("child_cnt=%d\n", child_cnt);
			for(i = 0; i < child_cnt; i++)
			{
				menu_para->del_param.index = i;
				menu_para->del_param.src = lv_obj_get_child(menu_para->ui_menu_list, 0);
				menu_para->ui_list_para->lbar_del(&menu_para->del_param);
			}
		}
	}
}

void ui_list_folder_create(ui_menu_para_t * menu_para, bool focused)
{
    uint32_t track_id, focused_id;
	//lv_obj_t* btn;

	__menu_msg("start_id = %d, item_cnt=%d, focus_id=%d\n", menu_para->ui_list_para->start_id, menu_para->ui_list_para->item_cnt, menu_para->ui_list_para->focus_id);
	if(menu_para->ui_list_para->item_cnt)
	{
		menu_para->ui_list_para->end_id = menu_para->ui_list_para->start_id + menu_para->ui_list_para->item_cnt - 1;
		menu_para->ui_list_para->page_end_id = menu_para->ui_list_para->start_id + menu_para->ui_list_para->item_cnt;
		menu_para->ui_list_para->page_start_id = menu_para->ui_list_para->start_id;
		focused_id = menu_para->ui_list_para->focus_id;
		if((menu_para->ui_list_para->item_cnt > 0) && ((menu_para->ui_list_para->item_cnt) > menu_para->ui_list_para->max_item_num))//总条目大于最大条目数
		{
			if((focused_id >= menu_para->ui_list_para->page_start_id) && (focused_id < menu_para->ui_list_para->page_end_id))//聚焦条目在范围内
			{
				if((menu_para->ui_list_para->page_end_id - focused_id) < menu_para->ui_list_para->lbar_page_num)//聚焦条目后面不足一页
				{
					menu_para->ui_list_para->page_start_id = menu_para->ui_list_para->page_end_id - menu_para->ui_list_para->max_item_num;
				}
				else
				{
					if((focused_id - menu_para->ui_list_para->page_start_id) < menu_para->ui_list_para->max_fornt_num)//聚焦条目前面不足两页
					{
						menu_para->ui_list_para->page_end_id = menu_para->ui_list_para->page_start_id + menu_para->ui_list_para->max_item_num;
					}
					else
					{
						menu_para->ui_list_para->page_start_id = focused_id - menu_para->ui_list_para->max_fornt_num;//前两页
						menu_para->ui_list_para->page_end_id = focused_id + menu_para->ui_list_para->lbar_page_num;//后一页
					}
				}
				
				if(!focused)
					focused_id = menu_para->ui_list_para->focus_id - menu_para->ui_list_para->page_start_id;
				else
					focused_id = 0;
			}
			else
			{
				menu_para->ui_list_para->page_end_id = menu_para->ui_list_para->page_start_id + menu_para->ui_list_para->max_item_num;
				focused_id = 0;
			}
			
		}
		else
		{
			if((focused_id >= menu_para->ui_list_para->page_start_id) && (focused_id < menu_para->ui_list_para->page_end_id))
			{
			    if(!focused)
					focused_id = menu_para->ui_list_para->focus_id - menu_para->ui_list_para->start_id;
				else
					focused_id = 0;
			}
			else
			{
				focused_id = 0;
			}
	    }
	    
		//__menu_msg("list_track_last_id = %d, page_start_id = %d, page_end_id=%d, focused_id=%d\n", menu_para->list_track_last_id, menu_para->ui_list_para->page_start_id, menu_para->ui_list_para->page_end_id, focused_id);
		//btn = ui_list_btn(menu_para, menu_para->ui_list_para->start_id);//第一个条目文件夹名
		for(track_id = menu_para->ui_list_para->page_start_id; track_id < menu_para->ui_list_para->page_end_id; track_id++)
		{
			menu_para->draw_param.index = track_id;
			menu_para->ui_list_para->lbar_draw(&menu_para->draw_param);
			//btn = ui_list_btn(menu_para, track_id);
				
			if(menu_para->ui_list_para->focus_id == track_id)
			{
				if(focused)
					focused_id = track_id - menu_para->ui_list_para->page_start_id;
				//menu_para->list_track_id = track_id - menu_para->ui_list_para->page_start_id + 1;
				//__menu_msg("menu_para->list_track_id=%d\n", menu_para->list_track_id);
			}
		}
		
		__menu_msg("focused_id=%d\n", focused_id);
		//if(focused)
	    	lv_obj_scroll_to_view(lv_obj_get_child(menu_para->ui_menu_list, focused_id), LV_ANIM_OFF);

	    if(menu_para->ui_list_para->item_cnt > menu_para->ui_list_para->lbar_page_num)
	    {
	    	__u32 slider_height;
	    	__u32 slider_y;
			__s32 item_height = menu_para->ui_list_para->item_height;
			__u32 start_id = menu_para->ui_list_para->start_id;
			__u32 page_start_id = menu_para->ui_list_para->page_start_id;
			__u32 item_cnt = menu_para->ui_list_para->item_cnt;
			__u32 lbar_page_num = menu_para->ui_list_para->lbar_page_num;
			lv_coord_t ui_menu_list_h = lv_obj_get_height(menu_para->ui_menu_list);
	    	
			lv_obj_clear_flag(menu_para->ui_list_scroll_bar, LV_OBJ_FLAG_HIDDEN);	  /// Flags

			slider_height = ui_menu_list_h * (lbar_page_num * item_height) / (item_cnt * item_height);
			__menu_msg("slider_height=%d, ui_menu_list_h=%d, lbar_page_num=%d, item_cnt=%d, item_height=%d\n", slider_height, ui_menu_list_h, lbar_page_num, item_cnt, item_height);
			lv_obj_set_height(menu_para->ui_list_scroll_bar, slider_height);			

			if(focused)
			{
				if((((page_start_id - start_id) + focused_id) <= lbar_page_num))
					slider_y = 0;
				else
					slider_y = (ui_menu_list_h - slider_height) *((focused_id + page_start_id - lbar_page_num) * item_height) / ((item_cnt	- lbar_page_num) * item_height);

				__menu_msg("slider_y=%d, page_start_id=%d, start_id=%d, focused_id=%d\n", slider_y, page_start_id, start_id, focused_id);
				
				if(slider_y > (ui_menu_list_h - slider_height))
				{
					slider_y = (ui_menu_list_h - slider_height);
				}

				lv_obj_set_y(menu_para->ui_list_scroll_bar, slider_y);
			}
		}
		else
		{
			lv_obj_add_flag(menu_para->ui_list_scroll_bar, LV_OBJ_FLAG_HIDDEN);	  /// Flags
		}
		menu_para->list_scroll_flag = 1;
		__menu_msg("1:page_start_id = %d, item_cnt=%d, page_end_id=%d\n", menu_para->ui_list_para->page_start_id, menu_para->ui_list_para->item_cnt, menu_para->ui_list_para->page_end_id);
    }
}

void ui_list_folder_destroy(ui_menu_para_t * menu_para)
{
	__menu_msg("0:lv_obj_get_child_cnt(ui_menu_para->ui_menu_list)=%d\n", lv_obj_get_child_cnt(menu_para->ui_menu_list));
	if(lv_obj_get_child_cnt(menu_para->ui_menu_list))
	{
		menu_para->list_scroll_flag = 0;
		ui_list_del_all_item(menu_para);
		lv_obj_clean(menu_para->ui_menu_list);//删除父对象下的子对象，不删除本身
	}
	__menu_msg("1:lv_obj_get_child_cnt(ui_menu_para->ui_menu_list)=%d\n", lv_obj_get_child_cnt(menu_para->ui_menu_list));
}

static void ui_list_pic_create(ui_menu_para_t * menu_para)
{
    uint32_t track_id, focused_id;

	if(menu_para->ui_list_para->item_cnt > PIC_PAGE_TOTAL_ITEM)
	{
		menu_para->ui_list_para->page_end_id = PIC_PAGE_TOTAL_ITEM;
	}
	else
	{
		menu_para->ui_list_para->page_end_id = menu_para->ui_list_para->item_cnt;
	}
	menu_para->ui_list_para->page_start_id = 0;
	
	__menu_msg("menu_para->ui_list_para.item_cnt=%d\n", menu_para->ui_list_para->item_cnt);
	for(track_id = menu_para->ui_list_para->page_start_id; (track_id < menu_para->ui_list_para->item_cnt) && (track_id < PIC_PAGE_TOTAL_ITEM); track_id++)
	{
		menu_para->draw_param.index = track_id;
		menu_para->ui_list_para->lbar_draw(&menu_para->draw_param);
	}
}

static void ui_menu_switch(ui_menu_para_t * menu_para, __u8 media_type)
{
	rat_media_type_t media_file_type = 0;
	int dirindex = 0;
	int dirfiletotal = 0;

	/*if((menu_para->mode == APP_MOVIE_ID) || (menu_para->mode == APP_MUSIC_ID) || (menu_para->mode == APP_BT_AUDIO_ID))
	{
		__menu_msg("switch media_type = %d\n", media_type);
		menu_para->draw_param.type = media_type;
		menu_para->ui_list_para->media_type = media_type;
		menu_para->ui_list_para->rat.handle = NULL;

		ui_menu_set_type_icon(menu_para);
		ui_explorer_rat_init(menu_para->ui_list_para);
		ui_explorer_get_last_para(menu_para->ui_list_para);
			
		menu_para->ui_list_para->start_id = GetListItemDirIndex(menu_para->ui_list_para->rat.handle, menu_para->ui_list_para->focus_id);
		menu_para->ui_list_para->item_cnt = GetListItemDirFileTotal(menu_para->ui_list_para->rat.handle,menu_para->ui_list_para->start_id);
#ifdef USE_MENU_USB_NO_FOLDER
		if(menu_para->mode == APP_MUSIC_ID)
		{
			menu_para->ui_list_para->start_id++;
			menu_para->ui_list_para->item_cnt--;
		}
#endif
		
		ui_list_folder_destroy(menu_para);
		ui_list_folder_create(menu_para, 1);
	}*/
}

///////////////////// EVENT FUNCTIONS ////////////////////
void ui_event_menu_List(lv_event_t* e)
{
    static bool flag = 0;
    static lv_coord_t scroll_y = 0;
    static lv_coord_t begin_scroll_y = 0;
	uint32_t ii = 0;
	uint32_t cnt = 0;
	__u32 item_num = 0;
	ui_menu_para_t * menu_para = lv_event_get_user_data(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t* target = lv_event_get_target(e);
	lv_obj_t* child_obj = NULL;

	if(menu_para->list_scroll_flag)
	{
		if(event_code == LV_EVENT_SCROLL)
		{
			//LV_LOG_WARN("lv_obj_get_scroll_y=%d\n", lv_obj_get_scroll_y(target));
			//LV_LOG_WARN("lv_obj_get_scroll_top=%d\n", lv_obj_get_scroll_top(target));
			//LV_LOG_WARN("lv_obj_get_scroll_bottom=%d\n", lv_obj_get_scroll_bottom(target));
			if(flag == 0)
			{
				flag = 1;
				scroll_y = lv_obj_get_scroll_y(target);
				//__menu_msg("scroll_y=%d, begin_scroll_y=%d\n", scroll_y, begin_scroll_y);
				
				//if(scroll_y > 0)
				{
					if((scroll_y <= menu_para->ui_list_para->item_height) && (begin_scroll_y > menu_para->ui_list_para->item_height) && (menu_para->ui_list_para->page_start_id >= 1))//向上滚动
					{
						//__menu_msg("start_id=%d, page_start_id=%d\n", menu_para->ui_list_para->start_id, menu_para->ui_list_para->page_start_id);
						item_num = menu_para->ui_list_para->page_start_id - menu_para->ui_list_para->start_id;
						if(item_num >= menu_para->ui_list_para->lbar_page_num)
						{
							item_num = menu_para->ui_list_para->lbar_page_num;
						}
						//__menu_msg("item_num11=%d\n", item_num);
						//__menu_msg("list_track_last_id=%d, page_end_id=%d\n", menu_para->list_track_last_id, menu_para->ui_list_para->page_end_id);
						for(ii = 0; ii < item_num; ii++)
						{
							menu_para->ui_list_para->page_start_id--;
							menu_para->ui_list_para->page_end_id--;
							//if((menu_para->list_track_last_id >= menu_para->ui_list_para->page_start_id) && (menu_para->list_track_last_id < menu_para->ui_list_para->page_end_id))
							//	menu_para->list_track_id++;
							//else
							//	menu_para->list_track_id = 0;
							//__menu_msg("list_track_id11=%d\n", menu_para->list_track_id);
							menu_para->draw_param.index = menu_para->ui_list_para->page_start_id;
							child_obj = (lv_obj_t*)menu_para->ui_list_para->lbar_draw(&menu_para->draw_param);
							lv_obj_move_to_index(child_obj, 0);
							cnt = lv_obj_get_child_cnt(target);
							child_obj = lv_obj_get_child(target, cnt - 1);
							if(menu_para->ui_list_para->media_type == RAT_MEDIA_TYPE_PIC)
							{
								if(menu_para->ui_list_para->lbar_del)
								{
									menu_para->del_param.index = cnt - 1;
									menu_para->del_param.src = child_obj;
									menu_para->ui_list_para->lbar_del(&menu_para->del_param);
								}
							}
							else
							{
								lv_obj_del(child_obj);
							}
							scroll_y = lv_obj_get_scroll_y(target);
							lv_obj_scroll_to_y(target, scroll_y + menu_para->ui_list_para->item_height, LV_ANIM_OFF);
							//menu_para->list_scroll_bar_flag = 1;
						}
					}
					else if((scroll_y >= (lv_coord_t)((menu_para->ui_list_para->item_height * menu_para->ui_list_para->lbar_page_num * menu_para->ui_list_para->max_page_num - menu_para->ui_list_para->list_rect.height) - menu_para->ui_list_para->item_height)) 
						&& (begin_scroll_y < (lv_coord_t)((menu_para->ui_list_para->item_height * menu_para->ui_list_para->lbar_page_num * menu_para->ui_list_para->max_page_num - menu_para->ui_list_para->list_rect.height) - menu_para->ui_list_para->item_height))
						&& (menu_para->ui_list_para->page_end_id < (menu_para->ui_list_para->start_id + menu_para->ui_list_para->item_cnt)))//向下滚动
					{
						//__menu_msg("start_id=%d, page_end_id=%d, item_cnt=%d\n", menu_para->ui_list_para->start_id, menu_para->ui_list_para->page_end_id, menu_para->ui_list_para->item_cnt);
						item_num = menu_para->ui_list_para->start_id + menu_para->ui_list_para->item_cnt - menu_para->ui_list_para->page_end_id;
						if(item_num >= menu_para->ui_list_para->lbar_page_num)
						{
							item_num = menu_para->ui_list_para->lbar_page_num;
						}
						//__menu_msg("item_num22=%d\n", item_num);
						//__menu_msg("list_track_last_id=%d, page_start_id=%d\n", menu_para->list_track_last_id, menu_para->ui_list_para->page_start_id);
						for(ii = 0; ii < item_num; ii++)
						{
							if(menu_para->ui_list_para->media_type == RAT_MEDIA_TYPE_PIC)
							{
								if(menu_para->ui_list_para->lbar_del)
								{
									menu_para->del_param.index = 0;
									menu_para->del_param.src = lv_obj_get_child(target, 0);
									menu_para->ui_list_para->lbar_del(&menu_para->del_param);
								}
							}
							else
							{
								lv_obj_del(lv_obj_get_child(target, 0));
							}
							menu_para->draw_param.index = menu_para->ui_list_para->page_end_id;
							menu_para->ui_list_para->lbar_draw(&menu_para->draw_param);
							//ui_list_btn(menu_para, menu_para->ui_list_para->page_end_id);
							scroll_y = lv_obj_get_scroll_y(target);
							lv_obj_scroll_to_y(target, scroll_y - menu_para->ui_list_para->item_height, LV_ANIM_OFF);
							menu_para->ui_list_para->page_start_id++;
							menu_para->ui_list_para->page_end_id++;
							//if((menu_para->list_track_last_id >= menu_para->ui_list_para->page_start_id) && (menu_para->list_track_last_id < menu_para->ui_list_para->page_end_id))
							//	menu_para->list_track_id--;
							//else
							//	menu_para->list_track_id = 0;
							//__menu_msg("list_track_id22=%d\n", menu_para->list_track_id);

							//menu_para->list_scroll_bar_flag = 1;
						}
					}
#if 1
					else if(!menu_para->list_scroll_bar_flag && !menu_para->list_scroll_up_down_flag && !lv_obj_has_flag(menu_para->ui_list_scroll_bar, LV_OBJ_FLAG_HIDDEN))
					{
						__s32 slider_y;
						__s32 item_height = menu_para->ui_list_para->item_height;
						__u32 start_id = menu_para->ui_list_para->start_id;
						__u32 page_start_id = menu_para->ui_list_para->page_start_id;
						__u32 item_cnt = menu_para->ui_list_para->item_cnt;
						__u32 lbar_page_num = menu_para->ui_list_para->lbar_page_num;
						
						if(scroll_y > 0)
						{
							lv_coord_t ui_menu_h = lv_obj_get_height(menu_para->ui_menu);
							lv_coord_t ui_list_scroll_bar_h = lv_obj_get_height(menu_para->ui_list_scroll_bar);

							slider_y = (ui_menu_h - ui_list_scroll_bar_h) *(scroll_y + (page_start_id - start_id) * item_height) / ((item_cnt  - lbar_page_num) * item_height);
							//__menu_msg("ui_menu_h=%d, ui_list_scroll_bar_h=%d, slider_y=%d, scroll_y=%d, item_cnt=%d, item_height=%d\n", ui_menu_h, ui_list_scroll_bar_h, slider_y, scroll_y, item_cnt, item_height);
							if(slider_y > (ui_menu_h - ui_list_scroll_bar_h))
							{
								slider_y = (ui_menu_h - ui_list_scroll_bar_h);
							}
						}
						else
						{
							slider_y = 0;
						}
						
						lv_obj_set_y(menu_para->ui_list_scroll_bar, slider_y);
					}
#endif
				}
				begin_scroll_y = scroll_y;
				flag = 0;
			}
			
		}
		else if(event_code == LV_EVENT_SCROLL_BEGIN)
		{
			begin_scroll_y = lv_obj_get_scroll_y(target);
			//__menu_msg("LV_EVENT_SCROLL_BEGIN=%d\n", begin_scroll_y);
			//__menu_msg("xxxxx=%d\n", ((menu_para->ui_list_para->item_height * menu_para->ui_list_para->lbar_page_num * PAGE_NUM - menu_para->ui_list_para->list_rect.height) - menu_para->ui_list_para->item_height));
		}
		else  if(event_code == LV_EVENT_SCROLL_END)
		{
			//__menu_msg("LV_EVENT_SCROLL_END\n");
			begin_scroll_y = 0;
			scroll_y = 0;
			menu_para->list_scroll_up_down_flag = 0;
		}
	}
}
/*
static void ui_event_menu_top_browse(lv_event_t* e)
{
	ui_menu_para_t * menu_para = lv_event_get_user_data(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t * current_target = lv_event_get_current_target(e);

	if(event_code == LV_EVENT_PRESSED)
	{
		app_root_msg_send_opn(GUI_MSG_BEEP_SETTING,SEND_MCU_BEEP_SETTING_TIME,0,0,0,0,0);
	}
	else if(event_code == LV_EVENT_SHORT_CLICKED)
	{
		ui_menu_switch(menu_para, RAT_MEDIA_TYPE_AUDIO);
		lv_obj_add_state(menu_para->ui_menu_top_browse, LV_STATE_CHECKED);
		lv_obj_clear_state(menu_para->ui_menu_mid_browse, LV_STATE_CHECKED);
		lv_obj_clear_state(menu_para->ui_menu_bottom_browse, LV_STATE_CHECKED);
		if((menu_para->mode == APP_MOVIE_ID) || (menu_para->mode == APP_MUSIC_ID))
		{
			lv_obj_t * child;

			child = lv_obj_get_child(menu_para->ui_menu_top_browse, 0);
			if(child)
			{
				lv_obj_add_state(child, LV_STATE_CHECKED);
			}

			child = lv_obj_get_child(menu_para->ui_menu_mid_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}
				
			child = lv_obj_get_child(menu_para->ui_menu_bottom_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}
		}
	}
}

static void ui_event_menu_mid_browse(lv_event_t* e)
{
	ui_menu_para_t * menu_para = lv_event_get_user_data(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t * current_target = lv_event_get_current_target(e);

	if(event_code == LV_EVENT_PRESSED)
	{
		app_root_msg_send_opn(GUI_MSG_BEEP_SETTING,SEND_MCU_BEEP_SETTING_TIME,0,0,0,0,0);
	}
	else if(event_code == LV_EVENT_SHORT_CLICKED)
	{
		ui_menu_switch(menu_para, RAT_MEDIA_TYPE_VIDEO);
		lv_obj_clear_state(menu_para->ui_menu_top_browse, LV_STATE_CHECKED);
		lv_obj_add_state(menu_para->ui_menu_mid_browse, LV_STATE_CHECKED);
		lv_obj_clear_state(menu_para->ui_menu_bottom_browse, LV_STATE_CHECKED);
		if((menu_para->mode == APP_MOVIE_ID) || (menu_para->mode == APP_MUSIC_ID))
		{
			lv_obj_t * child;

			child = lv_obj_get_child(menu_para->ui_menu_top_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}

			child = lv_obj_get_child(menu_para->ui_menu_mid_browse, 0);
			if(child)
			{
				lv_obj_add_state(child, LV_STATE_CHECKED);
			}
				
			child = lv_obj_get_child(menu_para->ui_menu_bottom_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}
		}
	}
}

static void ui_event_menu_bottom_browse(lv_event_t* e)
{
	ui_menu_para_t * menu_para = lv_event_get_user_data(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t * current_target = lv_event_get_current_target(e);

	if(event_code == LV_EVENT_PRESSED)
	{
		app_root_msg_send_opn(GUI_MSG_BEEP_SETTING,SEND_MCU_BEEP_SETTING_TIME,0,0,0,0,0);
	}
	else if(event_code == LV_EVENT_SHORT_CLICKED)
	{
		ui_menu_switch(menu_para, RAT_MEDIA_TYPE_PIC);
		lv_obj_clear_state(menu_para->ui_menu_top_browse, LV_STATE_CHECKED);
		lv_obj_clear_state(menu_para->ui_menu_mid_browse, LV_STATE_CHECKED);
		lv_obj_add_state(menu_para->ui_menu_bottom_browse, LV_STATE_CHECKED);
		if((menu_para->mode == APP_MOVIE_ID) || (menu_para->mode == APP_MUSIC_ID))
		{
			lv_obj_t * child;

			child = lv_obj_get_child(menu_para->ui_menu_top_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}

			child = lv_obj_get_child(menu_para->ui_menu_mid_browse, 0);
			if(child)
			{
				lv_obj_clear_state(child, LV_STATE_CHECKED);
			}
				
			child = lv_obj_get_child(menu_para->ui_menu_bottom_browse, 0);
			if(child)
			{
				lv_obj_add_state(child, LV_STATE_CHECKED);
			}
		}
	}
}
*/
///////////////////// SCREENS ////////////////////
void ui_menu_screen_init(ui_menu_para_t * menu_para)
{
    menu_para->ui_menu = lv_obj_create(menu_para->ui_list_para->menu_obj);
    lv_obj_remove_style_all(menu_para->ui_menu);
    lv_obj_set_width(menu_para->ui_menu, lv_pct(100));
    lv_obj_set_height(menu_para->ui_menu, lv_pct(100));
    lv_obj_set_align(menu_para->ui_menu, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(menu_para->ui_menu, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_opa(menu_para->ui_menu, LV_OPA_TRANSP, 0);
	//eLIBs_printf("menu_para->ui_menu=0x%x\n", menu_para->ui_menu);

	menu_para->ui_menu_content = lv_img_create(menu_para->ui_menu);
	//lv_img_set_src(menu_para->ui_menu_content, ui_menu_get_res(menu_para, MENU_SETTING_CONTENT_BGD_BMP));
	lv_obj_set_width(menu_para->ui_menu_content, LV_SIZE_CONTENT);   /// 739
	lv_obj_set_height(menu_para->ui_menu_content, LV_SIZE_CONTENT);	/// 404
	lv_obj_add_flag(menu_para->ui_menu_content, LV_OBJ_FLAG_HIDDEN);	   /// Flags
	lv_obj_clear_flag(menu_para->ui_menu_content, LV_OBJ_FLAG_SCROLLABLE); 	 /// Flags

	menu_para->ui_menu_content_bg = lv_img_create(menu_para->ui_menu);
	//lv_img_set_src(menu_para->ui_menu_content_bg, ui_menu_get_res(menu_para, MENU_EXPLORER_BROWSE_TOP_BG_BMP));
	lv_obj_set_width(menu_para->ui_menu_content_bg, LV_SIZE_CONTENT);	 /// 739
	lv_obj_set_height(menu_para->ui_menu_content_bg, LV_SIZE_CONTENT);    /// 404
	lv_obj_add_flag(menu_para->ui_menu_content_bg, LV_OBJ_FLAG_HIDDEN);	  /// Flags
	lv_obj_clear_flag(menu_para->ui_menu_content_bg, LV_OBJ_FLAG_SCROLLABLE);		/// Flags

   /* menu_para->ui_menu_top_browse = lv_obj_create(menu_para->ui_menu);
    lv_obj_remove_style_all(menu_para->ui_menu_top_browse);
	lv_obj_set_width(menu_para->ui_menu_top_browse, lv_pct(20));
	lv_obj_set_height(menu_para->ui_menu_top_browse, lv_pct(50));
	lv_obj_add_flag(menu_para->ui_menu_top_browse, LV_OBJ_FLAG_ADV_HITTEST);	  /// Flags
	lv_obj_clear_flag(menu_para->ui_menu_top_browse, LV_OBJ_FLAG_SCROLLABLE);		/// Flags
	lv_obj_set_style_bg_color(menu_para->ui_menu_top_browse, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(menu_para->ui_menu_top_browse, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_bg_opa(menu_para->ui_menu_top_browse, 50, LV_PART_MAIN);
	lv_obj_set_style_border_width(menu_para->ui_menu_top_browse, 5, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_side(menu_para->ui_menu_top_browse, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_color(menu_para->ui_menu_top_browse, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
	//eLIBs_printf("menu_para->ui_menu_top_browse=0x%x\n", menu_para->ui_menu_top_browse);

	menu_para->ui_menu_mid_browse = lv_obj_create(menu_para->ui_menu);
    lv_obj_remove_style_all(menu_para->ui_menu_mid_browse);
	lv_obj_set_y(menu_para->ui_menu_mid_browse, lv_pct(50));
	lv_obj_set_width(menu_para->ui_menu_mid_browse, lv_pct(20));
	lv_obj_set_height(menu_para->ui_menu_mid_browse, lv_pct(50));
	lv_obj_add_flag(menu_para->ui_menu_mid_browse, LV_OBJ_FLAG_ADV_HITTEST);	  /// Flags
	lv_obj_clear_flag(menu_para->ui_menu_mid_browse, LV_OBJ_FLAG_SCROLLABLE);		/// Flags
	lv_obj_set_style_bg_color(menu_para->ui_menu_mid_browse, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(menu_para->ui_menu_mid_browse, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_bg_opa(menu_para->ui_menu_mid_browse, 50, 0);
	lv_obj_set_style_border_width(menu_para->ui_menu_mid_browse, 5, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_side(menu_para->ui_menu_mid_browse, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_color(menu_para->ui_menu_mid_browse, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
	//eLIBs_printf("menu_para->ui_menu_mid_browse=0x%x\n", menu_para->ui_menu_mid_browse);
	
	menu_para->ui_menu_bottom_browse = lv_obj_create(menu_para->ui_menu);
    lv_obj_remove_style_all(menu_para->ui_menu_bottom_browse);
	lv_obj_set_y(menu_para->ui_menu_bottom_browse, lv_pct(100));
	lv_obj_set_width(menu_para->ui_menu_bottom_browse, lv_pct(20));
	lv_obj_set_height(menu_para->ui_menu_bottom_browse, lv_pct(50));
	lv_obj_add_flag(menu_para->ui_menu_bottom_browse, LV_OBJ_FLAG_ADV_HITTEST);	 /// Flags
	lv_obj_clear_flag(menu_para->ui_menu_bottom_browse, LV_OBJ_FLAG_SCROLLABLE);	   /// Flags
	lv_obj_set_style_bg_color(menu_para->ui_menu_bottom_browse, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(menu_para->ui_menu_bottom_browse, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_bg_opa(menu_para->ui_menu_bottom_browse, 50, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(menu_para->ui_menu_bottom_browse, 10, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_side(menu_para->ui_menu_bottom_browse, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_CHECKED);
	lv_obj_set_style_border_color(menu_para->ui_menu_bottom_browse, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);*/

	menu_para->ui_menu_list = lv_obj_create(menu_para->ui_menu);
	lv_obj_remove_style_all(menu_para->ui_menu_list);
    //lv_obj_remove_style(menu_para->ui_menu_list, NULL, LV_PART_MAIN);
	lv_obj_set_x(menu_para->ui_menu_list, lv_pct(5));
	lv_obj_set_width(menu_para->ui_menu_list, lv_pct(95));
	lv_obj_set_height(menu_para->ui_menu_list, lv_pct(100));
	lv_obj_set_flex_flow(menu_para->ui_menu_list, LV_FLEX_FLOW_COLUMN);
	//lv_obj_set_scrollbar_mode(menu_para->ui_menu_list, LV_SCROLLBAR_MODE_AUTO);

	menu_para->ui_list_scroll_bar = lv_obj_create(menu_para->ui_menu);
	lv_obj_remove_style_all(menu_para->ui_list_scroll_bar);
	lv_obj_set_width(menu_para->ui_list_scroll_bar, 2);
	lv_obj_set_height(menu_para->ui_list_scroll_bar, lv_pct(100));
    lv_obj_set_align(menu_para->ui_list_scroll_bar, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(menu_para->ui_list_scroll_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(menu_para->ui_list_scroll_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(menu_para->ui_menu_list, ui_event_menu_List, LV_EVENT_ALL, menu_para);
	//lv_obj_add_event_cb(menu_para->ui_menu_top_browse, ui_event_menu_top_browse, LV_EVENT_ALL, menu_para);
	//lv_obj_add_event_cb(menu_para->ui_menu_mid_browse, ui_event_menu_mid_browse, LV_EVENT_ALL, menu_para);
	//lv_obj_add_event_cb(menu_para->ui_menu_bottom_browse, ui_event_menu_bottom_browse, LV_EVENT_ALL, menu_para);
}


static ui_menu_para_t * ui_menu_init(void * para)
{
	ui_menu_para_t *ui_menu_para;

	ui_menu_para = (ui_menu_para_t *)esMEMS_Balloc(sizeof(ui_menu_para_t));
	
	if(!ui_menu_para)
	{
		eLIBs_printf("ui_menu_para balloc fail!!!\n");
		return NULL;
	}
	eLIBs_memset((void*)ui_menu_para, 0, sizeof(ui_menu_para_t));

	ui_menu_para->ui_list_para = (explr_list_para_t*)para;
	ui_menu_init_res(ui_menu_para);
    ui_menu_screen_init(ui_menu_para);
	//eLIBs_printf("ui_menu_screen_init ui_menu_para=0x%x\n", ui_menu_para);

	return ui_menu_para;
}

static void ui_menu_uninit(ui_menu_para_t *ui_menu_para)
{
	if(ui_menu_para)
	{
		eLIBs_printf("ui_menu_para = 0x%x, ui_menu=0x%x\n", ui_menu_para, ui_menu_para->ui_menu);
		lv_obj_del(ui_menu_para->ui_menu);
		eLIBs_printf("11111\n");
		ui_menu_para->ui_menu = NULL;
		ui_menu_uninit_res(ui_menu_para);
		eLIBs_printf("2222222\n");
		esMEMS_Bfree(ui_menu_para, sizeof(ui_menu_para_t));
		eLIBs_printf("33333333\n");
		ui_menu_para = NULL;
	}
}

void * ui_menu_create(explr_list_para_t* ui_list_para, __u32 mode)
{
	ui_menu_para_t * ui_menu_para;

	ui_menu_para = ui_menu_init(ui_list_para);
	if (ui_menu_para == NULL)
    {
        return NULL;
    }

	//gscene_bgd_set_img_src(BG_INDEX_COMMON);
	
	ui_menu_para->ui_list_para = ui_list_para;
	ui_menu_para->mode = mode;
	ui_menu_para->draw_param.attr = ui_list_para->list_attr;
	ui_menu_para->draw_param.type = ui_list_para->media_type;
	ui_menu_para->del_param.attr = ui_list_para->list_attr;
	ui_menu_para->del_param.type = ui_list_para->media_type;
	//ui_menu_set_type_icon(ui_menu_para);
	
	/*Be sure the screens layout is correct*/
	lv_obj_update_layout(ui_menu_para->ui_menu);
	
	ui_list_para->item_obj = ui_menu_para->ui_menu_list;
	
	/*if((mode == APP_SMENU_ID) && (ui_list_para->media_type == RAT_MEDIA_TYPE_PIC))
	{
		ui_list_para->item_width = lv_obj_get_width(ui_menu_para->ui_menu_list);//570;
		ui_list_para->item_height = 126;
		ui_list_para->list_rect.x = 0;
		ui_list_para->list_rect.y = 0;
		ui_list_para->list_rect.width = 570;
		ui_list_para->list_rect.height = 378;//380;
		ui_list_para->lbar_page_num = ui_list_para->list_rect.height/ui_list_para->item_height;
		ui_list_para->max_item_num = PIC_PAGE_TOTAL_ITEM;
		ui_list_para->max_page_num = PIC_PAGE_NUM;
		ui_list_para->max_fornt_num = PIC_PAGE_FORNT_ITEM;
	}
	else if(mode == APP_BLE_SMENU_WIRELESS_ID)
	{
		ui_list_para->item_width = lv_obj_get_width(ui_menu_para->ui_menu_list);//570;
		ui_list_para->item_height = ui_list_para->item_width/PAGE_ITEM_NUM;//76;
		ui_list_para->list_rect.x = 0;
		ui_list_para->list_rect.y = 0;
		ui_list_para->list_rect.width = ui_list_para->item_width;//570;
		ui_list_para->list_rect.height = 76;
		ui_list_para->lbar_page_num = ui_list_para->list_rect.height/ui_list_para->item_height;
		ui_list_para->max_item_num = PAGE_TOTAL_ITEM;
		ui_list_para->max_page_num = PAGE_NUM;
		ui_list_para->max_fornt_num = PAGE_FORNT_ITEM;
	}
	else if((mode == APP_MUSIC_ID) || (mode == APP_MOVIE_ID) || (mode == APP_BT_AUDIO_ID))
	{
#if 1		
		__menu_msg("__ui_menu_create_mode_APP_BT_AUDIO_ID......\n");
		ui_list_para->list_rect.x = 0;
		ui_list_para->list_rect.y = 0;
		ui_list_para->list_rect.width = lv_obj_get_width(ui_menu_para->ui_menu_list);//570;
		ui_list_para->list_rect.height = lv_obj_get_height(ui_menu_para->ui_menu_list);
		ui_list_para->item_width = ui_list_para->list_rect.width;//570;
		ui_list_para->item_height = 76;//ui_list_para->list_rect.height/(PAGE_ITEM_NUM - 1);//76;
		ui_list_para->lbar_page_num = ui_list_para->list_rect.height/ui_list_para->item_height;
		ui_list_para->max_item_num = (PAGE_NUM * (PAGE_ITEM_NUM - 1));
		ui_list_para->max_page_num = PAGE_NUM;
		ui_list_para->max_fornt_num = ((PAGE_NUM * (PAGE_ITEM_NUM - 1)) - (PAGE_ITEM_NUM - 1));
#else
		ui_list_para->list_rect.x = 0;
		ui_list_para->list_rect.y = 0;
		ui_list_para->list_rect.width = lv_obj_get_width(ui_menu_para->ui_menu_list);//570;
		ui_list_para->list_rect.height = lv_obj_get_height(ui_menu_para->ui_menu_list);
		ui_list_para->item_width = ui_list_para->list_rect.width;//570;
		ui_list_para->item_height = ui_list_para->list_rect.height/(PAGE_ITEM_NUM - 1);//76;
		ui_list_para->lbar_page_num = ui_list_para->list_rect.height/ui_list_para->item_height;
		ui_list_para->max_item_num = (PAGE_NUM * (PAGE_ITEM_NUM - 1));
		ui_list_para->max_page_num = PAGE_NUM;
		ui_list_para->max_fornt_num = ((PAGE_NUM * (PAGE_ITEM_NUM - 1)) - (PAGE_ITEM_NUM - 1));
#endif
	}
	else*/
	{
		ui_list_para->list_rect.x = 0;
		ui_list_para->list_rect.y = 0;
		ui_list_para->list_rect.width = lv_obj_get_width(ui_menu_para->ui_menu_list);//570;
		ui_list_para->list_rect.height = lv_obj_get_height(ui_menu_para->ui_menu_list);//380;
		ui_list_para->item_width = ui_list_para->list_rect.width;//570;
		ui_list_para->item_height = ui_list_para->list_rect.height/PAGE_ITEM_NUM;//76;
		ui_list_para->lbar_page_num = ui_list_para->list_rect.height/ui_list_para->item_height;
		ui_list_para->max_item_num = PAGE_TOTAL_ITEM;
		ui_list_para->max_page_num = PAGE_NUM;
		ui_list_para->max_fornt_num = PAGE_FORNT_ITEM;
	}
	//lv_obj_set_height(ui_menu_para->ui_menu_list, ui_list_para->list_rect.height);
    __menu_msg("item_width=%d\n", ui_list_para->item_width);
    __menu_msg("item_height=%d\n", ui_list_para->item_height);
    __menu_msg("list_rect.width=%d\n", ui_list_para->list_rect.width);
    __menu_msg("list_rect.height=%d\n", ui_list_para->list_rect.height);
    __menu_msg("lbar_page_num=%d\n", ui_list_para->lbar_page_num);
    __menu_msg("max_item_num=%d\n", ui_list_para->max_item_num);
    __menu_msg("max_page_num=%d\n", ui_list_para->max_page_num);
    __menu_msg("max_fornt_num=%d\n", ui_list_para->max_fornt_num);

	/*if(((mode == APP_MOVIE_ID) || (mode == APP_MUSIC_ID)) && (ui_menu_para->ui_list_para->rat.handle == NULL))
	{
		ui_explorer_rat_init(ui_menu_para->ui_list_para);
		ui_explorer_get_last_para(ui_menu_para->ui_list_para);
		
		ui_menu_para->ui_list_para->start_id = GetListItemDirIndex(ui_menu_para->ui_list_para->rat.handle, ui_menu_para->ui_list_para->focus_id);
		ui_menu_para->ui_list_para->item_cnt = GetListItemDirFileTotal(ui_menu_para->ui_list_para->rat.handle,ui_menu_para->ui_list_para->start_id);
#ifdef USE_MENU_USB_NO_FOLDER
		if((ui_menu_para->mode == APP_MUSIC_ID))
		{
			ui_menu_para->ui_list_para->start_id++;
			ui_menu_para->ui_list_para->item_cnt--;
		}
	    __menu_msg("__ui_menu_create: focus_id=%d, start_id=%d, item_cnt=%d\n", ui_menu_para->ui_list_para->focus_id, ui_menu_para->ui_list_para->start_id, ui_menu_para->ui_list_para->item_cnt);
#endif
	}*/
	
	ui_list_folder_create(ui_menu_para, 1);

	lv_obj_set_user_data(ui_menu_para->ui_menu, ui_menu_para);
    __menu_msg("__ui_menu_create end\n");
    
	return (void *)ui_menu_para->ui_menu;
}

void ui_menu_destroy(void * para)
{
	ui_menu_para_t * ui_menu_para = (ui_menu_para_t *)lv_obj_get_user_data((lv_obj_t *)para);
	//ui_menu_para_t * ui_menu_para = (ui_menu_para_t *)para;

	__menu_msg("__ui_menu_destroy:ui_menu_para=0x%x\n", ui_menu_para);
	if(ui_menu_para)
	{
		ui_menu_uninit(ui_menu_para);
		
	}
}

