obj-y += ui_main.o
obj-y += ui_manger.o

#obj-y += widgets/ui_radio.o
obj-y += widgets/ui_status_bar.o
obj-y += widgets/ui_quick_access.o
obj-y += widgets/ui_clock.o
obj-y += widgets/ui_sys_control.o

# 开发模板（仅供参考，不参与编译）
# obj-y += widgets/ui_widget_template.o
obj-y += widgets/ui_source.o
obj-y += screens/ui_screens.o
obj-y += screens/ui_screens_bg.o

obj-y += listbar/ui_menu.o
obj-y += listbar/ui_menu_res.o